# -*- coding: utf-8 -*-
"""cc-007/6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/gist/taydin7/5f1068ab5196e14e9ca97c70e11bbb38/cc-007-6.ipynb
"""

number = int(input("Find prime numbers  : "))

for num in range(2, number + 1):

    i = 1

    for i in range(2, num):
        if(num % i == 0):
            i = num
            break;

    # If the number is prime then print it.
    if(i != num):
        print(num, end=" ")