# -*- coding: utf-8 -*-
"""countletter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qsd0ZCQYwbP_Qfd6smxJSbXYNbw0fzOv
"""

sentence= input("Please enter a sentence :")
word_dict={}

for n in sentence:
  keys= word_dict.keys()
  if n in keys:
    word_dict[n] +=1
  else:
    word_dict[n]=1
word_dict